application: coursera-chat
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: latest

builtins:
- appstats: on
- remote_api: on

handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.app
